# Reporting: wragle_report

## Data Gathering
In the cell below, I gather **all** three pieces of data for this project and load them in the notebook. **Note:** the methods required to gather each data are different.

### Download data
      a. twitter_archive_enhanced.csv
      b. image_predictions.tsv
      c. tweet_json.txt

### Quality issues
1. Column tweet_id is wrong type. Convert to Int

2. Columns: retweet_count and favorite_count should be integers, not floats. Convert to Int.

3. Columns unused for analysis should be drop (text, in_reply_to_status_id, in_reply_to_user_id)

4. The timestamp column has wrong type. Convert to datetime type.

5. Some tweet are just a retweet from origin

6. Column expanded_urls has rows with null values. 

7. Source column is in HTML-formatted string, not a normal string

8. Dog names not corrected

### Tidiness issues
9. Columns: doggo, floofer, pupper, and puppo should be replace with one category column name dog_type.

10. Twitter API table and Image prediction table should be merged into Twitter archive table

## Cleaning Data
In this section, clean **all** of the issues you documented while assessing. 

**Note:** Make a copy of the original data before cleaning. Cleaning includes merging individual pieces of data according to the rules of [tidy data](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html). The result should be a high-quality and tidy master pandas DataFrame (or DataFrames, if appropriate).

### Issue #1:

#### Define: Column tweet_id is wrong type. Convert to Int

#### Code

In [101]:
df_twitter_archive.tweet_id = df_twitter_archive.tweet_id.astype('int64')

#### Test

In [102]:
type(df_twitter_archive.tweet_id[0])

numpy.int64

### Issue #2:

#### Define: retweet_count and favorite_count should be integers, not floats. Convert to Int

#### Code

In [103]:
df_tweet_json.favorite_count = df_tweet_json.favorite_count.astype(int)
df_tweet_json.retweet_count = df_tweet_json.retweet_count.astype(int)

#### Test

In [104]:
type(df_tweet_json.favorite_count[0])

numpy.int64

In [105]:
type(df_tweet_json.retweet_count[0])

numpy.int64

### Issue #3:

#### Define: Columns unused for analysis should be drop (text, in_reply_to_status_id, in_reply_to_user_id)

#### Code

In [106]:
df_twitter_archive = df_twitter_archive.drop(['text', 'in_reply_to_status_id', 'in_reply_to_user_id'], axis=1)

#### Test

In [107]:
df_twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 14 columns):
tweet_id                      2356 non-null int64
timestamp                     2356 non-null object
source                        2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(2), int64(3), object(9)
memory usage: 257.8+ KB

### Issue #4:

#### Define: The timestamp column has wrong type. Convert to datetime type.

#### Code

In [108]:
df_twitter_archive.timestamp = df_twitter_archive.timestamp.astype('datetime64')

#### Test

In [109]:
type(df_twitter_archive.timestamp[0])

pandas._libs.tslibs.timestamps.Timestamp

In [110]:
df_twitter_archive.timestamp[0]

Timestamp('2017-08-01 16:23:56')

### Issue #5:

#### Define: Remove retweet rows

#### Code

In [111]:
df_twitter_archive = df_twitter_archive[df_twitter_archive['retweeted_status_id'].isna() |
                                       df_twitter_archive['retweeted_status_user_id'].isna() |
                                       df_twitter_archive['retweeted_status_timestamp'].isna()]

#### Test

In [112]:
# Percentage of null values in columns
df_twitter_archive.isna().sum() * 100 /len(df_twitter_archive)

tweet_id                        0.000000
timestamp                       0.000000
source                          0.000000
retweeted_status_id           100.000000
retweeted_status_user_id      100.000000
retweeted_status_timestamp    100.000000
expanded_urls                   2.666667
rating_numerator                0.000000
rating_denominator              0.000000
name                            0.000000
doggo                           0.000000
floofer                         0.000000
pupper                          0.000000
puppo                           0.000000
dtype: float64

In [113]:
df_twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 14 columns):
tweet_id                      2175 non-null int64
timestamp                     2175 non-null datetime64[ns]
source                        2175 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2117 non-null object
rating_numerator              2175 non-null int64
rating_denominator            2175 non-null int64
name                          2175 non-null object
doggo                         2175 non-null object
floofer                       2175 non-null object
pupper                        2175 non-null object
puppo                         2175 non-null object
dtypes: datetime64[ns](1), float64(2), int64(3), object(8)
memory usage: 254.9+ KB

### Issue #6:

#### Define: Column expanded_urls has rows with null values.

#### Code

In [114]:
df_twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 14 columns):
tweet_id                      2175 non-null int64
timestamp                     2175 non-null datetime64[ns]
source                        2175 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2117 non-null object
rating_numerator              2175 non-null int64
rating_denominator            2175 non-null int64
name                          2175 non-null object
doggo                         2175 non-null object
floofer                       2175 non-null object
pupper                        2175 non-null object
puppo                         2175 non-null object
dtypes: datetime64[ns](1), float64(2), int64(3), object(8)
memory usage: 254.9+ KB

In [115]:
df_twitter_archive = df_twitter_archive[df_twitter_archive['expanded_urls'].notna()]

#### Test

In [116]:
df_twitter_archive.expanded_urls.isna().sum()

0

### Issue #7:

#### Define: Source column is in HTML-formatted string, not a normal string

#### Code

In [117]:
df_twitter_archive.source.value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     1985
<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>                          91
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                       30
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>      11
Name: source, dtype: int64

In [118]:
#extract values
df_twitter_archive.source = df_twitter_archive.source.str.extract('>([\w\W\s]*)<', expand=True)

#### Test

In [119]:
df_twitter_archive.source.value_counts()

Twitter for iPhone     1985
Vine - Make a Scene      91
Twitter Web Client       30
TweetDeck                11
Name: source, dtype: int64

### Issue #8:

#### Define: Drop row which dog names not corrected

#### Code

In [120]:
wrong_name = ['a', 'actually', 'all', 'an', 'by', 'getting', 'his', 'incredibly', 'infuriating',
'just', 'life', 'light', 'mad', 'my', 'not', 'officially', 'old', 'one', 'quite',
'space', 'such', 'the', 'this', 'unacceptable','very']

In [121]:
df_twitter_archive = df_twitter_archive.loc[~df_twitter_archive['name'].isin(wrong_name)]

#### Test

In [122]:
mask = df_twitter_archive.name.str.contains('^[a-z]', regex = True)
df_twitter_archive[mask].name.value_counts().sort_index()

Series([], Name: name, dtype: int64)

### Issue #9:

#### Define: Replace doggo, floofer, pupper, and puppo columns with one category column name dog_type and drop them after that

#### Code

In [123]:
df_twitter_archive['add_all'] = df_twitter_archive.doggo + df_twitter_archive.floofer + df_twitter_archive.pupper + df_twitter_archive.puppo

In [124]:
df_twitter_archive.add_all.value_counts()

NoneNoneNoneNone        1689
NoneNonepupperNone       211
doggoNoneNoneNone         70
NoneNoneNonepuppo         23
doggoNonepupperNone        9
NoneflooferNoneNone        9
doggoflooferNoneNone       1
doggoNoneNonepuppo         1
Name: add_all, dtype: int64

In [125]:
df_twitter_archive['dog_stage'] = df_twitter_archive['add_all'].astype('str')

In [126]:
df_twitter_archive['dog_stage'] = df_twitter_archive['dog_stage'].str.replace("None", "")

In [127]:
df_twitter_archive = df_twitter_archive.drop(['doggo', 'floofer', 'pupper', 'puppo'], axis=1)

#### Test

In [128]:
df_twitter_archive.dog_stage.value_counts()

                1689
pupper           211
doggo             70
puppo             23
floofer            9
doggopupper        9
doggofloofer       1
doggopuppo         1
Name: dog_stage, dtype: int64

### Issue #10:

#### Define: Twitter API table and Image prediction table should be merged into Twitter archive table

#### Code

In [129]:
df_final_data = pd.merge(df_twitter_archive, df_image, on = "tweet_id", how = "left")

In [130]:
df_tweet_json["tweet_id"]  = df_tweet_json["tweet_id"].astype(int)

In [131]:
df_final_data = pd.merge(df_final_data, df_tweet_json, on = "tweet_id", how = "left")

#### Test

In [132]:
df_final_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2013 entries, 0 to 2012
Data columns (total 28 columns):
tweet_id                      2013 non-null int64
timestamp                     2013 non-null datetime64[ns]
source                        2013 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2013 non-null object
rating_numerator              2013 non-null int64
rating_denominator            2013 non-null int64
name                          2013 non-null object
add_all                       2013 non-null object
dog_stage                     2013 non-null object
jpg_url                       1896 non-null object
img_num                       1896 non-null float64
p1                            1896 non-null object
p1_conf                       1896 non-null float64
p1_dog                        1896 non-null object
p2                            1896 non-null object
p2_conf                       1896 non-null float64
p2_dog                        1896 non-null object
p3                            1896 non-null object
p3_conf                       1896 non-null float64
p3_dog                        1896 non-null object
favorite_count                2013 non-null int64
followers_count               2013 non-null int64
retweet_count                 2013 non-null int64
retweeted                     2013 non-null bool
truncated                     2013 non-null bool
dtypes: bool(2), datetime64[ns](1), float64(6), int64(6), object(13)
memory usage: 428.5+ KB

## Storing Data
Save gathered, assessed, and cleaned master dataset to a CSV file named "twitter_archive_master.csv".

In [139]:
df_final_data.to_csv("twitter_archive_final.csv", index=False)

## Analyzing and Visualizing Data
In this section, analyze and visualize your wrangled data. You must produce at least **three (3) insights and one (1) visualization.**

In [140]:
df_final_data = pd.read_csv('twitter_archive_final.csv')
df_final_data

,tweet_id,timestamp,source,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,...,p2_conf,p2_dog,p3,p3_conf,p3_dog,favorite_count,followers_count,retweet_count,retweeted,truncated
0,892420643555336193,2017-08-01 16:23:56,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,...,0.085851,False,banana,0.076110,False,39467,3200889,8853,False,False
1,892177421306343426,2017-08-01 00:17:27,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,...,0.090647,True,papillon,0.068957,True,33819,3200889,6514,False,False
2,891815181378084864,2017-07-31 00:18:03,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,...,0.078253,True,kelpie,0.031379,True,25461,3200889,4328,False,False
3,891689557279858688,2017-07-30 15:58:51,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,...,0.168086,True,spatula,0.040836,False,42908,3200889,8964,False,False
4,891327558926688256,2017-07-29 16:00:24,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,...,0.225770,True,German_short-haired_pointer,0.175219,True,41048,3200889,9774,False,False
5,891087950875897856,2017-07-29 00:08:17,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891087950...,13,10,None,...,0.116317,True,Indian_elephant,0.076902,False,20562,3200889,3261,False,False
6,890971913173991426,2017-07-28 16:27:12,Twitter for iPhone,NaN,NaN,NaN,"https://gofundme.com/ydvmve-surgery-for-jax,ht...",13,10,Jax,...,0.199287,True,ice_lolly,0.193548,False,12041,3200889,2158,False,False
7,890729181411237888,2017-07-28 00:22:40,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890729181...,13,10,None,...,0.178406,True,Pembroke,0.076507,True,56848,3200889,16716,False,False
8,890609185150312448,2017-07-27 16:25:51,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890609185...,13,10,Zoey,...,0.193054,True,Chesapeake_Bay_retriever,0.118184,True,28226,3200889,4429,False,False
9,890240255349198849,2017-07-26 15:59:51,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890240255...,14,10,Cassie,...,0.451038,True,Chihuahua,0.029248,True,32467,3200889,7711,False,False
10,890006608113172480,2017-07-26 00:31:25,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890006608...,13,10,Koda,...,0.013884,True,chow,0.008167,True,31166,3200889,7624,False,False
11,889880896479866881,2017-07-25 16:11:53,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889880896...,13,10,Bruno,...,0.151317,True,muzzle,0.082981,False,28268,3200889,5156,False,False
12,889665388333682689,2017-07-25 01:55:32,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889665388...,13,10,None,...,0.027356,True,basenji,0.004633,True,38818,3200889,8538,False,False
13,889638837579907072,2017-07-25 00:10:02,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889638837...,12,10,Ted,...,0.002129,True,Staffordshire_bullterrier,0.001498,True,27672,3200889,4735,False,False
14,889531135344209921,2017-07-24 17:02:04,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889531135...,13,10,Stuart,...,0.013834,True,redbone,0.007958,True,15359,3200889,2321,False,False
15,889278841981685760,2017-07-24 00:19:32,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889278841...,13,10,Oliver,...,0.194742,True,Saluki,0.027351,True,25652,3200889,5637,False,False
16,888917238123831296,2017-07-23 00:22:39,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888917238...,12,10,Jim,...,0.120184,True,Labrador_retriever,0.105506,True,29611,3200889,4709,False,False
17,888804989199671297,2017-07-22 16:56:37,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888804989...,13,10,Zeke,...,0.184172,True,English_setter,0.073482,True,26080,3200889,4559,False,False
18,888554962724278272,2017-07-22 00:23:06,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888554962...,13,10,Ralphus,...,0.166511,True,malamute,0.111411,True,20290,3200889,3732,False,False
19,888078434458587136,2017-07-20 16:49:33,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888078434...,12,10,Gerald,...,0.000932,True,bull_mastiff,0.000903,True,22201,3200889,3653,False,False
20,887705289381826560,2017-07-19 16:06:48,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887705289...,13,10,Jeffrey,...,0.087582,True,Weimaraner,0.026236,True,30779,3200890,5609,False,False
21,887473957103951883,2017-07-19 00:47:34,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,...,0.054950,True,beagle,0.038915,True,69871,3200890,18781,False,False
22,887343217045368832,2017-07-18 16:08:03,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887343217...,13,10,None,...,0.275645,False,Weimaraner,0.134203,True,34222,3200890,10737,False,False
23,887101392804085760,2017-07-18 00:07:08,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887101392...,12,10,None,...,0.035029,True,Staffordshire_bullterrier,0.029705,True,31061,3200890,6167,False,False
24,886983233522544640,2017-07-17 16:17:36,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886983233...,13,10,Maya,...,0.143528,True,can_opener,0.032253,False,35859,3200890,8084,False,False
25,886736880519319552,2017-07-16 23:58:41,Twitter for iPhone,NaN,NaN,NaN,"https://www.gofundme.com/mingusneedsus,https:/...",13,10,Mingus,...,0.186136,True,Dandie_Dinmont,0.086346,True,12306,3200890,3443,False,False
26,886680336477933568,2017-07-16 20:14:00,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886680336...,13,10,Derek,...,0.139952,False,car_wheel,0.044173,False,22798,3200890,4610,False,False
27,886366144734445568,2017-07-15 23:25:31,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886366144...,12,10,Roscoe,...,0.000361,True,Boston_bull,0.000076,True,21524,3200890,3316,False,False
28,886258384151887873,2017-07-15 16:17:19,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886258384...,13,10,Waffles,...,0.025286,False,Siamese_cat,0.002849,False,28469,3200890,6523,False,False
29,885984800019947520,2017-07-14 22:10:11,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/885984800...,12,10,Jimbo,...,0.006630,True,Bernese_mountain_dog,0.006239,True,33382,3200890,7097,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1983,666786068205871104,2015-11-18 01:12:41,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666786068...,2,10,None,...,0.000055,False,acorn,0.000026,False,800,3201018,521,False,False
1984,666776908487630848,2015-11-18 00:36:17,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666776908...,5,10,Josep,...,0.167175,True,Chihuahua,0.086951,True,368,3201018,186,False,False
1985,666739327293083650,2015-11-17 22:06:57,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666739327...,10,10,Lugan,...,0.165255,True,toy_poodle,0.095959,True,244,3201018,71,False,False
1986,666691418707132416,2015-11-17 18:56:35,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666691418...,8,10,Christoper,...,0.008687,True,bloodhound,0.005394,True,196,3201018,51,False,False
1987,666649482315059201,2015-11-17 16:09:56,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666649482...,4,10,None,...,0.170497,True,collie,0.139206,True,923,3201017,608,False,False
1988,666644823164719104,2015-11-17 15:51:26,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666644823...,9,10,Jimothy,...,0.043209,True,West_Highland_white_terrier,0.038906,True,238,3201017,88,False,False
1989,666454714377183233,2015-11-17 03:16:00,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666454714...,10,10,Kreggory,...,0.237612,True,Great_Pyrenees,0.171106,True,545,3201017,223,False,False
1990,666447344410484738,2015-11-17 02:46:43,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666447344...,9,10,Scout,...,0.287955,True,Labrador_retriever,0.166331,True,107,3201017,23,False,False
1991,666437273139982337,2015-11-17 02:06:42,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666437273...,7,10,None,...,0.124680,True,Saluki,0.044094,True,131,3201017,52,False,False
1992,666435652385423360,2015-11-17 02:00:15,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666435652...,10,10,None,...,0.056775,False,power_drill,0.036763,False,170,3201017,54,False,False
1993,666430724426358785,2015-11-17 01:40:41,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666430724...,6,10,None,...,0.104109,True,dingo,0.062071,False,330,3201017,204,False,False
1994,666428276349472768,2015-11-17 01:30:57,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666428276...,7,10,None,...,0.249394,True,Pomeranian,0.241878,True,171,3201017,90,False,False
1995,666421158376562688,2015-11-17 01:02:40,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666421158...,12,10,None,...,0.090346,True,Shih-Tzu,0.001117,True,327,3201017,118,False,False
1996,666418789513326592,2015-11-17 00:53:15,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666418789...,10,10,Walter,...,0.148258,True,Chihuahua,0.142860,True,129,3201017,48,False,False
1997,666396247373291520,2015-11-16 23:23:41,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666396247...,9,10,None,...,0.009397,True,papillon,0.004577,True,172,3201018,92,False,False
1998,666373753744588802,2015-11-16 21:54:18,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666373753...,11,10,None,...,0.259551,True,briard,0.206803,True,194,3201018,100,False,False
1999,666362758909284353,2015-11-16 21:10:36,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666362758...,6,10,None,...,0.002402,False,hamster,0.000461,False,804,3201018,595,False,False
2000,666353288456101888,2015-11-16 20:32:58,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666353288...,8,10,None,...,0.147655,True,Eskimo_dog,0.093412,True,229,3201018,77,False,False
2001,666345417576210432,2015-11-16 20:01:42,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666345417...,10,10,None,...,0.054787,True,Labrador_retriever,0.014241,True,307,3201018,146,False,False
2002,666273097616637952,2015-11-16 15:14:19,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666273097...,11,10,None,...,0.111884,True,basenji,0.111152,True,184,3201018,82,False,False
2003,666268910803644416,2015-11-16 14:57:41,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666268910...,10,10,None,...,0.085547,False,bookcase,0.079480,False,108,3201018,37,False,False
2004,666104133288665088,2015-11-16 04:02:55,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666104133...,1,10,None,...,0.033919,False,partridge,0.000052,False,14765,3201018,6871,False,False
2005,666102155909144576,2015-11-16 03:55:04,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666102155...,11,10,None,...,0.149842,True,borzoi,0.133649,True,81,3201018,16,False,False
2006,666099513787052032,2015-11-16 03:44:34,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666099513...,8,10,None,...,0.166192,True,Dandie_Dinmont,0.089688,True,164,3201018,73,False,False
2007,666094000022159362,2015-11-16 03:22:39,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666094000...,9,10,None,...,0.078260,True,malinois,0.075628,True,169,3201018,79,False,False
2008,666082916733198337,2015-11-16 02:38:37,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666082916...,6,10,None,...,0.404722,True,French_bulldog,0.048960,True,121,3201018,47,False,False
2009,666073100786774016,2015-11-16 01:59:36,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666073100...,10,10,None,...,0.175382,True,Ibizan_hound,0.097471,True,335,3201018,174,False,False
2010,666071193221509120,2015-11-16 01:52:02,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666071193...,9,10,None,...,0.174201,True,Pekinese,0.109454,True,154,3201018,67,False,False
2011,666049248165822465,2015-11-16 00:24:50,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,...,0.243682,True,Doberman,0.154629,True,111,3201018,41,False,False
2012,666020888022790149,2015-11-15 22:32:08,Twitter for iPhone,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,...,0.156665,True,Shetland_sheepdog,0.061428,True,2535,3201018,532,False,False

### Insights:
1. Year with most twitter

2. Source with most twitter

3. Dog with most popular name

In [1]:
from subprocess import call
call(['python', '-m', 'nbconvert', 'wrangle_report.ipynb'])

0